# .github/workflows/gem-push.yml
name: Ruby Gem – Build & Publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    # 没有任何 *.gemspec 文件 → 整个 Job 跳过
    if: ${{ hashFiles('*.gemspec') != '' }}

    runs-on: ubuntu-latest   # GitHub Official runner (ubuntu-24.04)
    permissions:
      contents: read
      packages: write        # 如果以后想推到 GitHub Packages 也OK

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # ---------- 以下步骤仅当你日后真的添加 gemspec 时才会执行 ----------
      - name: Build gem
        run: gem build *.gemspec
